# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
target 'TaskXische' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskXische

  target 'TaskXischeTests' do
    #pod 'RealmSwift'
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaskXischeUITests' do
    # Pods for testing
  end

end
